config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :menus do
      resources :menu_items
      resources :menu_item_eval_strings, :controller => "menu_items"
      resources :menu_item_links, :controller => "menu_items"
      resources :menu_item_pages, :controller => "menu_items"
      resources :menu_item_products, :controller => "menu_items"
    end
    resources :menu_items
  end
  match 'admin/menus/:menu_id/menu_items/:id/move_up' => "admin/menu_items#move_up", :via => :get, :as => :move_up_admin_menu_menu_items
  match 'admin/menus/:menu_id/menu_items/:id/move_down' => "admin/menu_items#move_down", :via => :get, :as => :move_down_admin_menu_menu_items
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	has_many :menu_items, :order => :position
	has_many :root_menu_items, :conditions => "`parent_id` IS NULL", :class_name => "MenuItem"

  def root_items
    if first = root_menu_items.first
      first.self_and_siblings
    else
      []
    end
  end

end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
	belongs_to :menu
	belongs_to :menu_item
	
	belongs_to :menuable, :polymorphic => true

  has_attached_file :mouse_out, :styles => { :thumb=> "100x100#" }
  has_attached_file :mouse_over, :styles => { :thumb=> "100x100#" }
  has_attached_file :mouse_down, :styles => { :thumb=> "100x100#" }

  acts_as_nested_set(:scope => :menu)

  Types = {
    :MenuItemPage => "Page",
    :MenuItemProduct => "Product",
    :MenuItemLink => "Link",
    :MenuItemEvalString => "Evaluated Expression"
  }

  def content
    self.menuable_content
  end

  def content_type
    self.class.name.to_s.gsub("MenuItem","")
  end

  def linkable
    "#"
  end

  def onclick
    "return false;"
  end
end

app/models/menu_item_eval_string.rb
class MenuItemEvalString < MenuItem

end

app/models/menu_item_link.rb
class MenuItemLink < MenuItem


  def onclick
    ""
  end

  def linkable
    self.menuable_content
  end  

end

app/models/menu_item_page.rb
class MenuItemPage < MenuItem

  def onclick
    ""
  end

  def linkable
    (self.menuable)? self.menuable.link : "#"
  end  

end

app/models/menu_item_product.rb
class MenuItemProduct < MenuItem

  def onclick
    ""
  end

  def linkable
    self.menuable
  end  

end

app/controllers/admin/menu_items_controller.rb
class Admin::MenuItemsController < Admin::BaseController
  resource_controller
  
  before_filter :load_resources

  def move_down
    @menu_item = MenuItem.find(params[:id])

	  respond_to do |format|
      if @menu_item.move_right
  		  format.html { redirect_to( admin_menu_menu_items_path(@menu) ) }
      else
  		  format.html { redirect_to( admin_menu_menu_items_path(@menu) ) }
      end
	  end  
  end

  def move_up
    @menu_item = MenuItem.find(params[:id])

	  respond_to do |format|
      if @menu_item.move_left
  		  format.html { redirect_to( admin_menu_menu_items_path(@menu) ) }
      else
  		  format.html { redirect_to( admin_menu_menu_items_path(@menu) ) }
      end
	  end  
  end

  def index   

	  respond_to do |format|
		  format.html { render :action => :index }
	  end  
  end
  
  def new
    @menu = Menu.find(params[:menu_id])
	  @menu_item = MenuItem.new(:menu => @menu)
    
	  respond_to do |format|
		  format.html { render :action => :new, :layout => false }
	  end  
  end
  
  def edit
	  @menu_item = MenuItem.find(params[:id])
	  @menu = @menu_item.menu
    
	  respond_to do |format|
		  format.html { render :action => :edit }
	  end    
  end

  def create
    klass = ( ((!params[:type].to_s.empty?)? params[:type] : nil) || "MenuItem").constantize

    @menu_item = klass.new(params[:menu_item])

	  respond_to do |format|
      if @menu_item.save
  		  format.html { redirect_to( admin_menu_menu_items_path(@menu) ) }
      else
  		  format.html { redirect_to( admin_menu_menu_items_path(@menu) ) }
      end
	  end  
  end

  def update
    key = ( params[:klass] || "MenuItem").classify.tableize.singularize.to_sym

    @menu_item = MenuItem.find(params[:id])
    @menu_item.type = params[:type]

	  respond_to do |format|
      if @menu_item.update_attributes( params[key] )
  		  format.html { redirect_to( admin_menu_menu_items_path(@menu) ) }
      else
  		  format.html { redirect_to( admin_menu_menu_items_path(@menu) ) }
      end
	  end  
  end

  
  # override the destory method to set deleted_at value
  # instead of actually deleting the product.
  def destroy
    @menu_item = MenuItem.find_by_id(params[:id])

    if @menu_item.destroy
      flash[:notice] = I18n.t("notice_messages.menu_item_deleted")
    else
      flash[:notice] = I18n.t("notice_messages.menu_item_not_deleted")
    end

    respond_to do |format|
      format.html { redirect_to collection_url }
      format.js  { render_js_for_destroy }
    end
  end

  def load_resources
	  @menu = Menu.find(params[:menu_id])

    @pages = Page.find_by_sql("SELECT * FROM `pages` ORDER BY `title` ")
    @products = Product.find_by_sql("SELECT * FROM `products` WHERE `deleted_at` IS NULL ORDER BY `name` ")
    @menu_items = @menu.root_items
  end

end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < Admin::BaseController
  resource_controller

  def new

    respond_to do |format|
      format.js { render :action => "new", :layout => false }
    end
  end
  
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to edit_admin_menu_path(@menu) }
      else
        format.html { redirect_to admin_menus_url }
      end
    end
  end

end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper

  def menu_dropdown_flyout(obj, selected, depth = 0) 

    obj = obj.root_items if obj.class == Menu

    content_tag("ul", (depth == 0)? { :class => 'menu-manager-dropdown-flyout' } : {} ) do 
      obj.collect.with_index { |i,index|
        content_tag("li", (depth == 0)? { :class => "button" } : {} ) do

          if depth == 0

            content_tag("div", :class => "parent #{ (index==obj.length-1)? 'last-parent' : '' }" ) do
              link_to( i.name, i.linkable )+""+     
              if i.children.length > 0       
                content_tag("div", :class => "dropdown" ) do
                  menu_dropdown_flyout(i.children, selected, depth+1)
                end 
              else
                ""
              end
            end 

          else

            link_to( i.name, i.linkable )+
            content_tag("div", "", { :class => "mini-zone" })+
            if i.children.length > 0       
              content_tag("div") do
                  menu_dropdown_flyout(i.children, selected, depth+1)
              end
            else
              ""
            end

          end


        end+"".html_safe
      }.join("").html_safe
    end

  end


end

app/helpers/menus_helper.rb
module MenusHelper

  def menu_dropdown_flyout(obj, selected, depth = 0) 

    obj = obj.root_items if obj.class == Menu

    content_tag("ul", (depth == 0)? { :class => 'menu-manager-dropdown-flyout' } : {} ) do 
      obj.collect.with_index { |i,index|
        content_tag("li", (depth == 0)? { :class => "button" } : {} ) do

          if depth == 0

            content_tag("div", :class => "parent #{ (index==obj.length-1)? 'last-parent' : '' }" ) do
              link_to( i.name, i.linkable )+""+     
              if i.children.length > 0       
                content_tag("div", :class => "dropdown" ) do
                  menu_dropdown_flyout(i.children, selected, depth+1)
                end 
              else
                ""
              end
            end 

          else

            link_to( i.name, i.linkable )+
            content_tag("div", "", { :class => "mini-zone" })+
            if i.children.length > 0       
              content_tag("div") do
                  menu_dropdown_flyout(i.children, selected, depth+1)
              end
            else
              ""
            end

          end


        end+"".html_safe
      }.join("").html_safe
    end

  end


end

app/views/admin/menu_items/_form.html.erb
<% id = (menu_item.new_record?)? "new" : menu_item.id %>
<% @captured_templates = {} %>

<%= form_for( [:admin,@menu,menu_item],  :html => { :multipart => true } ) do |f| %>
<%= hidden_field_tag :klass, menu_item[:type] unless menu_item.new_record? || menu_item[:type].to_s.empty? %>
<%= f.hidden_field :menu_id %>
<fieldset>
  <%= content_tag("h1") do %>
    <%= (menu_item.new_record?)? "New" : "Edit" %> Item
  <% end %>

  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %> <span class="required">*</span><br />
    <%= f.text_field :name, :class => 'title'  %>
    <%= f.error_message_on :name %>
  <% end %>

  <%= f.field_container :type do %>
    <%= label_tag :type, t("type") %>
    <%= select_tag :type, options_for_select( MenuItem::Types.to_a.collect { |i| i.reverse }.unshift([]), menu_item[:type] ),  { :onchange => "toggle_#{id}_menu_item_type(this)" } %>
  <% end %>
  <%= f.field_container :type do %>
      <%= f.label :parent_id, t("parent") %>
      <%= f.select :parent_id, nested_set_options(@menu_items, menu_item) {|i| "#{'--' * i.level} #{i.name}" }.unshift( ["-- Root Group --",'']  ) %>
      <%= f.error_message_on :parent_id %>
  <% end %>

  <% @captured_templates[:menu_item_pages] = capture do %>
  <div id="menu_item_page">
    <h2>Details</h2>
    <%= hidden_field_tag :type, "MenuItemPage" %>
    <%= f.hidden_field :menuable_type, { :value => "Page" } %>

    <table style="width:auto;">
    <tr>
      <td><%= f.label :menuable_id, t("page_title") %></td>
      <td><%= f.select :menuable_id, @pages.collect { |i| [i.title,i.id] }, { :include_blank => true }, {} %>
      <%= f.error_message_on :menuable_id %></td>
    </tr>
    </table>
  </div>
  <% end %>

  <% @captured_templates[:menu_item_products] = capture do %>
  <div id="menu_item_product">
    <h2>Details</h2>
    <%= hidden_field_tag :type, "MenuItemProduct" %>
    <%= f.hidden_field :menuable_type, { :value => "Product" } %>

    <table style="width:auto;">
    <tr>
      <td><%= f.label :menuable_id, t("product") %></td>
      <td><%= f.select :menuable_id, @products.collect { |i| [i.name,i.id] }, { :include_blank => true }, {} %>
      <%= f.error_message_on :menuable_id %></td>
    </tr>
    </table>
  </div>
  <% end %>

  <% @captured_templates[:menu_item_links] = capture do %>
  <div id="menu_item_link">
    <h2>Details</h2>
    <%= hidden_field_tag :type, "MenuItemLink" %>
    <table style="width:auto;">
    <tr>
      <td><%= f.label :menuable_content, t("link") %></td>
      <td><%= f.text_field :menuable_content %>
      <%= f.error_message_on :menuable_content %></td>
    </tr>
    </table>
  </div>
  <% end %>

  <% @captured_templates[:menu_item_eval_strings] = capture do %>
  <div id="menu_item_link">
    <h2>Details</h2>
    <%= hidden_field_tag :type, "MenuItemEvalString" %>
    <table style="width:auto;">
    <tr>
      <td><%= f.label :menuable_content, t("expression") %></td>
      <td><%= f.text_field :menuable_content %>
      <%= f.error_message_on :menuable_content %></td>
    </tr>
    </table>
  </div>
  <% end %>

  <div id="menu_item_content"><%= @captured_templates[ menu_item[:type].to_s.tableize.to_sym ] %></div>

  <div class="yui-gb">
    <div class="yui-u first">

 
    </div>
    <div class="yui-u">

    </div>
  </div>

	<%= submit_tag (menu_item.new_record?)? t("actions.create") : t("actions.update") %> 
	<%= t("or") %> 
	<%= link_to_function t("actions.cancel"), "$(this).closest('form').remove();" %>

</fieldset>
<% end %>

<%= content_for :head do %>

<% javascript_tag do %>

function toggle_<%= id %>_menu_item_type(select) {
  var $select = $(select),
      templates = {
        "MenuItemPage" : "<%= escape_javascript(@captured_templates[:menu_item_pages]) %>",
        "MenuItemProduct" : "<%= escape_javascript(@captured_templates[:menu_item_products]) %>",
        "MenuItemLink" : "<%= escape_javascript(@captured_templates[:menu_item_links]) %>",
        "MenuItemEvalString" : "<%= escape_javascript(@captured_templates[:menu_item_eval_strings]) %>"
      };

  if( $select.val() == "" ) {

    $("#menu_item_content").html("");

  } else {

    $("#menu_item_content").html( templates[ $select.val() ] );

  }
}

<% end %>


<% end %>

app/views/admin/menu_items/_index_row.html.erb
<% content_for :head do %>

<% javascript_tag do %>

	function edit_<%= menu_item.id %>_menu_item() {

		var template = "<%= escape_javascript( render( :partial => 'form', :locals => { :menu_item => menu_item } ).html_safe ) %>";

		$("#menu_item").html( template );

	}

<% end %>

<% end %>

<% depth ||= 0 %>

<tr valign="middle" id="<%= dom_id menu_item %>">
    <%- locals = {:menu_item => menu_item} -%>

    <td>
      <div style="display:block;float:left;font-size:4px;padding-left:<%= depth*10 %>px;width:10px;padding-top:2px;padding-right:2px;">        
        <%= link_to image_tag("admin/icons/up.gif", :border => 0), move_up_admin_menu_menu_items_path(@menu.id, menu_item.id), { :style => (!menu_item.left_sibling)? "visibility:hidden;" : "" }  %>&nbsp;
        <%= link_to image_tag("admin/icons/arrow-down.gif", :border => 0), move_down_admin_menu_menu_items_path(@menu.id, menu_item.id), { :style => (!menu_item.right_sibling)? "visibility:hidden;" : "" } %>
      </div>
      <div style="font-size:12px;"><%= menu_item.name %></div>
    </td>
		<td><%= menu_item.content_type -%></td>
		<td>
			<% if menu_item.mouse_out && menu_item.mouse_over && menu_item.mouse_down %>
				<%= image_tag menu_item.mouse_out.url(:original), { 	
										   	:onmouseover => "this.src = '#{menu_item.mouse_over.url(:original)}'",
										   	:onmouseout => "this.src = '#{menu_item.mouse_out.url(:original)}'",
										   	:onmousedown => "this.src = '#{menu_item.mouse_down.url(:original)}'",
										   	:onmouseup => "this.src = '#{menu_item.mouse_over.url(:original)}'",
											} 
				-%>
		</td>
		<td><%= menu_item.menuable_content %></td>
    <% end %>
    <td class="actions" width="120px">
        <%= link_to_edit menu_item, { :url => edit_admin_menu_menu_item_path(@menu,menu_item), :onclick => "edit_#{ menu_item.id }_menu_item(); return false;" } %>
        &nbsp;
        <%= link_to_delete menu_item, { :url => admin_menu_menu_item_path(@menu,menu_item) } %>
    </td>
</tr>
<% menu_item.children.each { |i| %>
	<%= render :partial => "index_row", :locals => { :menu_item => i, :depth => (depth+1) } %>	
<% } %>

app/views/admin/menu_items/index.html.erb
<% content_for :head do %>

<% javascript_tag do %>

	function new_menu_item() {

		var template = "<%= escape_javascript( render( :partial => 'form', :locals => { :menu_item => MenuItem.new(:menu => @menu) } ).html_safe ) %>";

		$("#menu_item").html( template );

	}
	
<% end %>

<% end %>


<%= render :partial => 'admin/shared/menu_tabs', :locals => {:current => "Menu Items"} %>

<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to_function t("new_menu_item"), "new_menu_item()", { :icon => 'add', :id => 'admin_new_menu_items_link' } -%>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("menu_items") %></h1>

<%= render :partial => 'admin/shared/menu_item_tabs', :locals => {:current => "List Items"} %>

<div id="menu_item"></div>

<table class="index" id='listing_menu_items'>

  <tr>

		  <th><%= t("name") %></th>
		  <th><%= t("content_type") %></th>
		  <th><%= t("image") %></th>
		  <th><%= t("content") %></th>

    <th>
      <%= hook :admin_menus_index_header_actions %>
    </th>
  </tr>
  <tbody>
    <% @menu_items.each do |menu_item| %>
	    <%= render :partial => "index_row", :locals => { :menu_item => menu_item, :depth => 0 } %>	
    <% end %>
  </tbody>
</table>

app/views/admin/menu_items/new.erb
<%= render "shared/error_messages", :target => @menu %>

<%= form_for(:menu,  :url => admin_menu_menu_items_url(@menu), :html => { :multipart => true }) do |f| %>
<fieldset>

  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %> <span class="required">*</span><br />
    <%= f.text_field :name, :class => 'title'  %>
    <%= f.error_message_on :name %>
  <% end %>


  <div class="yui-gb">
    <div class="yui-u first">

 
    </div>
    <div class="yui-u">

    </div>
  </div>

  <%= render :partial => 'admin/shared/new_ajax_blind_links' %>

</fieldset>
<% end %>

app/views/admin/menus/_form.html.erb
<div class="yui-gc">
  <div class="yui-u first">
    <%- locals = {:f => f} %>
    <%= hook :admin_menu_form_left, locals do %>
      <%= f.field_container :name do %>
        <%= f.label :name, t("name") %> <span class="required">*</span><br />
        <%= f.text_field :name, :class => 'fullwidth title'  %>
        <%= f.error_message_on :name %>
      <% end %>

      <%= f.field_container :placement do %>
        <%= f.label :placement, t("placement") %> <span class="required">*</span><br />
        <%= f.text_field :placement, :class => 'fullwidth title'  %>
        <%= f.error_message_on :placement %>
      <% end %>

    <% end %>
  </div>
  <div class="yui-u">

  </div>
</div>

app/views/admin/menus/edit.html.erb
<%= render :partial => 'admin/shared/menu_tabs', :locals => {:current => "Menu Details"} %>

<%= form_for(@menu, :url => object_url, :html => { :method => :put, :multipart => true }) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= render :partial => 'admin/shared/edit_resource_links' %>
<% end %>

app/views/admin/menus/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_menu"), new_object_url, { :remote => true, :icon => 'add', :id => 'admin_new_menus_link' } -%>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("menus") %></h1>

<div id="new_menu"></div>

<table class="index" id='listing_menus'>
  <tr>
    <%= hook :admin_menus_index_headers do %>
      <th><%= t("name") %></th>
      <th><%= t("placement") %></th>
    <% end %>
    <th>
      <%= hook :admin_menus_index_header_actions %>
    </th>
  </tr>
  <tbody>
    <% @menus.each do |method|%>
      <tr id="<%= dom_id method %>">
        <%- locals = {:method => method} %>
        <%= hook :admin_menus_index_rows, locals do %>
          <td width="120px"><%= method.name %></td>
          <td width="140px"><%= method.placement %></td>
        <% end %>
        <td width="140px">
          <%= hook :admin_menus_index_row_actions, locals do %>
            <%= link_to_edit method, :class => 'edit' %>
            &nbsp;
            <%= link_to_delete method %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/menus/new.erb
<%= render "shared/error_messages", :target => @menu %>

<%= form_for(:menu,  :url => collection_url, :html => { :multipart => true }) do |f| %>
<fieldset>

  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %> <span class="required">*</span><br />
    <%= f.text_field :name, :class => 'title'  %>
    <%= f.error_message_on :name %>
  <% end %>

  <%= f.field_container :placement do %>
    <%= f.label :placement, t("placement") %> <span class="required">*</span><br />
    <%= f.text_field :placement, :class => 'title'  %>
    <%= f.error_message_on :placement %>
  <% end %>


  <div class="yui-gb">
    <div class="yui-u first">

 
    </div>
    <div class="yui-u">

    </div>
  </div>

  <%= render :partial => 'admin/shared/new_resource_links' %>

</fieldset>
<% end %>

app/views/admin/shared/_menu_tabs.html.erb
<h1><%== t("editing_menu") + " &ldquo;#{@menu.name}&rdquo;" %></h1>

<% content_for :sidebar do %>

  <h3><%= @menu.name %></h3>
  <br class="clear" />

  <ul class="sidebar menu-menu">
    <%= hook :admin_menu_tabs, {:current => current} do %>

      <li<%== ' class="active"' if current == "Menu Details" %>>
        <%= link_to t("menu_details"), edit_admin_menu_url(@menu) %>
      </li>
      <li<%== ' class="active"' if current == "Menu Items" %>>
        <%= link_to t("menu_items"), admin_menu_menu_items_url(@menu) %>
      </li>      
    <% end %>
  </ul>
  <br class="clear" />

<% end %>